FROM nginx:latest
EXPOSE 80
COPY ./ImgCrop/docker/nginx.conf /etc/nginx/nginx.conf
COPY ./ImgCrop/docker/nginx_images /static
CMD ["nginx"]

# docker build -f Dockerfile_nginx -t nginx .
# docker run -p 80:80 --rm --name CN cnginx